/**
 * Created by hautruong on 7/7/18.
 */
// actions for artists
export const FETCH_SINGLE_ARTIST_SONGS = 'FETCH_SINGLE_ARTIST_SONGS';
export const FETCH_SINGLE_ARTIST_ALBUMS = 'FETCH_SINGLE_ARTIST_ALBUMS';
export const FETCH_SINGLE_ARTIST_BIOGRAPHY = 'FETCH_SINGLE_ARTIST_BIOGRAPHY';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_GENRE_ARTISTS_SUCCESS = 'FETCH_GENRE_ARTISTS_SUCCESS';
export const FETCH_GENRE_ARTISTS_ERROR = 'FETCH_GENRE_ARTISTS_ERROR';

export const FETCH_GENRE_DETAIL_ARTISTS_SUCCESS =
  'FETCH_GENRE_DETAIL_ARTISTS_SUCCESS';
export const FETCH_GENRE_DETAIL_ARTISTS_ERROR =
  'FETCH_GENRE_DETAIL_ARTISTS_ERROR';
export const CLEAR_ARTIST = 'CLEAR_ARTIST';
export const CLEAR_ARTISTS = 'CLEAR_ARTISTS';
