/**
 * Created by hautruong on 7/7/18.
 */
// actions for artists
export const FETCH_SINGLE_ARTIST_SONGS_SUCCESS =
  'FETCH_SINGLE_ARTIST_SONGS_SUCCESS';
export const FETCH_SINGLE_ARTIST_SONGS_ERROR =
  'FETCH_SINGLE_ARTIST_SONGS_ERROR';
export const FETCH_SINGLE_ARTIST_ALBUMS_SUCCESS =
  'FETCH_SINGLE_ARTIST_ALBUMS_SUCCESS';
export const FETCH_SINGLE_ARTIST_ALBUMS_ERROR =
  'FETCH_SINGLE_ARTIST_ALBUMS_ERROR';
export const FETCH_SINGLE_ARTIST_BIOGRAPHY_SUCCESS =
  'FETCH_SINGLE_ARTIST_BIOGRAPHY_SUCCESS';
export const FETCH_SINGLE_ARTIST_BIOGRAPHY_ERROR =
  'FETCH_SINGLE_ARTIST_BIOGRAPHY_ERROR';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_GENRE_ARTISTS_SUCCESS = 'FETCH_GENRE_ARTISTS_SUCCESS';
export const FETCH_GENRE_ARTISTS_ERROR = 'FETCH_GENRE_ARTISTS_ERROR';

export const FETCH_GENRE_DETAIL_ARTISTS_SUCCESS =
  'FETCH_GENRE_DETAIL_ARTISTS_SUCCESS';
export const FETCH_GENRE_DETAIL_ARTISTS_ERROR =
  'FETCH_GENRE_DETAIL_ARTISTS_ERROR';
export const CLEAR_ARTIST = 'CLEAR_ARTIST';
export const CLEAR_ARTISTS = 'CLEAR_ARTISTS';

export const FETCH_SINGLE_SONG_SUCCESS = 'FETCH_SINGLE_SONG_SUCCESS';
export const FETCH_SINGLE_SONG_ERROR = 'FETCH_SINGLE_SONG_ERROR';

export const FETCH_SUGGEST_SONG_SUCCESS = 'FETCH_SUGGEST_SONG_SUCCESS';
export const FETCH_SUGGEST_SONG_ERROR = 'FETCH_SUGGEST_SONG_ERROR';

export const REMOVE_SONG_FROM_QUEUE_SUCCESS = 'REMOVE_SONG_FROM_QUEUE_SUCCESS';
export const REMOVE_SONG_FROM_QUEUE_ERROR = 'REMOVE_SONG_FROM_QUEUE_ERROR';

export const TOGGLE_PUSH_ROUTE_SUCCESS = 'TOGGLE_PUSH_ROUTE_SUCCESS';
export const TOGGLE_PUSH_ROUTE_ERROR = 'TOGGLE_PUSH_ROUTE_ERROR';

export const ADD_SONG_TO_QUEUE_SUCCESS = 'ADD_SONG_TO_QUEUE_SUCCESS';
export const REPLACE_QUEUE_SUCCESS = 'REPLACE_QUEUE_SUCCESS';
export const CLEAR_QUEUE = 'CLEAR_QUEUE';
export const PLAY_USER_PLAYLIST = 'PLAY_USER_PLAYLIST';

// acitons for UI
export const SHOW_ANALYZER = 'SHOW_ANALYZER';
export const HIDE_ANALYZER = 'HIDE_ANALYZER';
export const TOGGLE_TRACK_DROPDOWN = 'TOGGLE_TRACK_DROPDOWN';
export const ADD_SONG_TO_QUEUE = 'ADD_SONG_TO_QUEUE';
export const TOGGLE_QUEUE = 'TOGGLE_QUEUE';
export const REPLACE_QUEUE = 'REPLACE_QUEUE';
export const REMOVE_SONG_FROM_QUEUE = 'REMOVE_SONG_FROM_QUEUE';
export const SLIDE_IN_RIGHT = 'SLIDE_IN_RIGHT';
export const RESET_SLIDE_IN_RIGHT = 'RESET_SLIDE_IN_RIGHT';
export const START_DOWNLOADING = 'START_DOWNLOADING';
export const FINISH_DOWNLOADING = 'FINISH_DOWNLOADING';
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const START_LOADING = 'START_LOADING';
export const FINISH_LOADING = 'FINISH_LOADING';
export const START_FADING = 'START_FADING';
export const STOP_FADING = 'STOP_FADING';

// actions for handling route transition
export const TOGGLE_PUSH_ROUTE = 'TOGGLE_PUSH_ROUTE';
export const UPDATE_PLAYED_PERCENT = 'UPDATE_PLAYED_PERCENT';
export const UPDATE_LYRIC_PERCENT = 'UPDATE_LYRIC_PERCENT';
export const UPDATE_LYRIC = 'UPDATE_LYRIC';
